# -*- coding: utf-8 -*-
"""vamshi_ineuron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZX4lFMHggF-yGUIJfCIIvAmSnRQVZSqr
"""

#Task1: 2nd solution#

n1=[]
for i in range(2000,3200):
    if (i%7==0) and (i%5!=0):
        n1.append(str(i))
print(','.join(n1))

#Task 1:3rd solution#

firstname=input("enter first name")
lastname=input("enter last name")
print(firstname[::-1] + " " +lastname[::-1])

#task1:4th solution#


r=12/2#d=r/2 where d=12#
V=4/3*3.14*r**3
print(V)

#Task2:1st solution#

values=input("enetr values")
list1=list(values.split(","))
print(list1)

#Task2:2nd solution#

for i in range(0,5):
    for j in range(i+1):
        print("*",end=" ")
    print(" ")
for i in range(5,1,-1):
    for j in range(i,1,-1):
        print("*",end=" ")
    print(" ")

#Task2:3rd solution#
    
string=input("enter string")
print(string[::-1])

#Task2:$th solution#
print("WE, THE PEOPLE OF INDIA,")
print("       having solemnly resolved to constitute India into a SOVEREIGN, !")
print("             SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC")
print("              and to secure to all its citizens")